WORD = 'word'
SEGMENT = 'segment'
FORMAT_JSON = 'json'
FORMAT_VERBOSE = 'verbose_json'
FORMAT_SRT = 'srt'
FORMAT_VTT = 'vtt'
DEVICE_CPU = 'cpu'
DEVICE_GPU = 'cuda'
VALID_RESPONSE_FORMAT = [
    FORMAT_JSON, FORMAT_VERBOSE, FORMAT_SRT, FORMAT_VTT
]